consumerKey: O0QnK3JsCXjLja4Tbk9h2NpWD
consumerSecret: IjM46sq1rQq5FTiBHloKT39zOukVj34UskTgX4UEGoPZboluSs
accessToken: 387030244-68bVpZQ2x5vninJVvhpGBRki6iqbzEHDjOY2XssE
accessTokenSecret: nfFxT4ak94YNrVz6SEk9TnXiXwyJYMBIRSpTXAeuCLSfk

kafkaHost: localhost:9092
stream_config:
  - kafka_topic: duyet
    twitter_keywords:
      - duyet
      - duyet.net
  - kafka_topic: uit
    twitter_keywords:
      - "#uit"
  - kafka_topic: fossil
    twitter_keywords:
      - "#fossil"
